# things not included
# git depth (not an issue with gh actions)
# languaage
# notifications - no email notifications set up
# completely lost on stages name/if section


name: pytest
on:
  pull_request:
    branches:
    - '*'
jobs:
  default:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.7]
    timeout-minutes: 30
    env:
      DESC: "Python 3.6 tests"  # f strings? is this even necessary?
      HV_REQUIREMENTS: "unit_tests"
      PYTHON_VERSION: ${{ matrix.python-version }}
      PKG_TEST_PYTHON: "--test-python=py37 --test-python=py27"
      CHANS_DEV: "-c pyviz/label/dev -c bokeh"
      CHANS: "-c pyviz"
      MPLBACKEND: "Agg"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pre_install
        run: |
          python -m pip install --upgrade pip
          pip install pyctdev flake8 nose
          doit miniconda_install
      - name: conda setup
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          conda config --set always_yes True
          conda install -c pyviz "pyctdev>=0.5"
          echo "second doit use"
          doit ecosystem_setup
      - name: install
        run: |
          doit env_create $CHANS_DEV --python=$PYTHON_VERSION
          eval "$(conda shell.bash hook)"
          conda activate test-environment

          doit develop_install $CHANS_DEV -o $HV_REQUIREMENTS
          doit env_capture
      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: flake8
        run: doit test_flakes

      - name: unit tests
        run: doit test_unit
      - name: test examples
        run: doit test_examples
    #   - name: test_all_recommended
    #     run: doit test_all_recommended
      - name: coveralls  # todo add if statement - if success coveralls, if fail, sleep 10 
        run: coveralls