# things not included
# git depth (not an issue with gh actions)
# languaage
# notifications - no email notifications set up
# completely lost on stages name/if section


name: pytest
on:
  pull_request:
    branches:
    - '*'
jobs:
  default:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.7]
    timeout-minutes: 30
    env:
      DESC: "Python 3.6 tests"  # f strings? is this even necessary?
      HV_REQUIREMENTS: "unit_tests"
      PYTHON_VERSION: ${{ matrix.python-version }}
      PKG_TEST_PYTHON: "--test-python=py37 --test-python=py27"
      CHANS_DEV: "-c pyviz/label/dev -c bokeh"
      CHANS: "-c pyviz"
      MPLBACKEND: "Agg"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pre_install
        run: |
          python -m pip install --upgrade pip
          pip install pyctdev flake8 nose
          doit miniconda_install
      - name: conda setup
        run: |
          export PATH="$HOME/miniconda/bin:$PATH" && hash -r
          conda config --set always_yes True
          conda install -c pyviz "pyctdev>=0.5"
          doit ecosystem_setup
          doit env_create ${CHANS_DEV} --python=${{ matrix.python-version }}
          eval "$(conda shell.bash hook)"
          conda activate test-environment
      - name: doit develop_install
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          conda list
          doit develop_install ${CHANS_DEV} -o ${HV_REQUIREMENTS}
      - name: doit env_capture
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          doit env_capture
      - name: conda list
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          conda list
      - name: doit test_flakes
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          doit test_flakes
      - name: doit test_unit
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          doit test_unit
      - name: test examples
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          doit test_examples
      - name: coveralls
        run: |
          ##vso[task.prependpath]($HOME)/miniconda/bin
          coveralls
